import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :obercloud_web, OberCloudWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# force_ssl is intentionally disabled in P0: the control plane serves plain HTTP
# on port 4000 with no TLS terminator in front of it.  When a load balancer or
# letsencrypt sidecar lands (P1+), re-enable force_ssl here and flip
# `scheme: "http"` → `"https"` in runtime.exs.
#
# config :obercloud_web, OberCloudWeb.Endpoint,
#   force_ssl: [
#     rewrite_on: [:x_forwarded_proto],
#     exclude: [
#       # paths: ["/health"],
#       hosts: ["localhost", "127.0.0.1"]
#     ]
#   ]

# Configure Swoosh API Client
config :swoosh, :api_client, Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
