defmodule OberCloud.Repo.Migrations.CreateDesiredState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:desired_state, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :resource_type, :text, null: false
      add :resource_id, :uuid, null: false
      add :spec, :map, null: false, default: %{}
      add :reconcile_status, :text, null: false, default: "pending"
      add :reconciled_at, :utc_datetime
      add :error, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :org_id,
          references(:organizations,
            column: :id,
            name: "desired_state_org_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :project_id,
          references(:projects,
            column: :id,
            name: "desired_state_project_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:desired_state, "desired_state_org_id_fkey")

    drop constraint(:desired_state, "desired_state_project_id_fkey")

    drop table(:desired_state)
  end
end
