defmodule OberCloud.Repo.Migrations.CreateMemberships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :org_id,
          references(:organizations,
            column: :id,
            name: "memberships_org_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "memberships_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:memberships, [:user_id, :org_id],
             name: "memberships_unique_user_org_index"
           )
  end

  def down do
    drop constraint(:memberships, "memberships_org_id_fkey")

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop_if_exists unique_index(:memberships, [:user_id, :org_id],
                     name: "memberships_unique_user_org_index"
                   )

    drop table(:memberships)
  end
end
