defmodule OberCloud.Repo.Migrations.CreateProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :org_id,
          references(:organizations,
            column: :id,
            name: "projects_org_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:projects, [:org_id, :slug], name: "projects_unique_slug_per_org_index")
  end

  def down do
    drop constraint(:projects, "projects_org_id_fkey")

    drop_if_exists unique_index(:projects, [:org_id, :slug],
                     name: "projects_unique_slug_per_org_index"
                   )

    drop table(:projects)
  end
end
